# Generated by Django 3.2.25 on 2024-03-31 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_security_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
