# Generated by Django 3.2.25 on 2024-03-24 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_extensions.db.fields
import worksifly.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfeature',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='securityfeature',
            name='likes',
        ),
        migrations.AddField(
            model_name='securityfeature',
            name='ingredients',
            field=models.TextField(default=datetime.datetime(2024, 3, 24, 14, 18, 44, 410456, tzinfo=utc), validators=[worksifly.validators.textfield_not_empty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityfeature',
            name='serch_time',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='securityfeature',
            name='setup_time',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
