# Generated by Django 3.2.25 on 2024-04-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksifly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfeature',
            name='ingredients',
        ),
    ]
