# Generated by Django 3.2.25 on 2024-03-09 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0002_auto_20240309_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfeature',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='securityfeature',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='securityfeature',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
