# Generated by Django 3.2.25 on 2024-03-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0003_auto_20240324_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityfeature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
