# Generated by Django 3.2.25 on 2024-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksifly', '0004_auto_20240309_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityfeature',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
