# Generated by Django 3.2.25 on 2024-03-25 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0004_alter_securityfeature_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 3, 25, 10, 21, 24, 699837, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_security_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='security_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security_items', to='worksifly.securityfeature'),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
