# Generated by Django 3.2.25 on 2024-03-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0005_alter_securityfeature_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityfeature',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_security_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_security_features_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
