# Generated by Django 3.2.25 on 2024-03-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksifly', '0005_auto_20240325_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfeature',
            name='ingredients',
        ),
    ]
