# Generated by Django 3.2.25 on 2024-03-28 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0006_remove_securityfeature_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='securityfeature',
            options={'ordering': ['-created_on'], 'verbose_name': 'Security Feature', 'verbose_name_plural': 'Security Features'},
        ),
        migrations.AlterModelOptions(
            name='techsecurityitem',
            options={'ordering': ['day'], 'verbose_name': 'Tech Security Item', 'verbose_name_plural': 'Tech Security Items'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='search_time',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='setup_time',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
