# Generated by Django 3.2.25 on 2024-03-30 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0007_auto_20240328_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='securityfeature',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='techsecurityitem',
            options={'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='securityfeature',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='0'),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='security_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security_item', to='worksifly.securityfeature'),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security', to=settings.AUTH_USER_MODEL),
        ),
    ]
