# Generated by Django 3.2.25 on 2024-03-30 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0008_auto_20240330_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
