# Generated by Django 3.2.25 on 2024-03-30 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksifly', '0009_securityfeature_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='securityfeature',
            options={'ordering': ['-created_on'], 'verbose_name': 'Security Feature', 'verbose_name_plural': 'Security Features'},
        ),
        migrations.AlterModelOptions(
            name='techsecurityitem',
            options={'ordering': ['day'], 'verbose_name': 'Tech Security Item', 'verbose_name_plural': 'Tech Security Items'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityfeature',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_security_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='security_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security_items', to='worksifly.securityfeature'),
        ),
        migrations.AlterField(
            model_name='techsecurityitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_security_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
